name: aws_request
description: Easily create, sign, and send API requests to AWS services without the hassle of implimenting Signature Version 4.
version: 0.4.0+1
homepage: https://github.com/Zsmerritt/Flutter_AWS_Request

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  intl: ^0.17.0 # Date Formatting
  crypto: ^3.0.0 # Key Signing
  http: ^0.13.0 # Send requests

dev_dependencies:
  test: ^1.16.0